export const segAssets = {
  primaryLogo: "/manus-storage/SEG_Primary_Logo_Approved_1f60ebe3.png",
  heroLogo: "/manus-storage/SEG_Hero_Logo_Heart_Brain_ECG_Approved_c28d10bb.png",
  officialBrainHeartMark: "/manus-storage/SEG_Official_Brain_Heart_Mark_Crop_a8cd393c.png",
  officialAppIcon: "/manus-storage/SEG_Official_App_Icon_Crop_4d97e4fa.png",
  brainHeartCore: "/manus-storage/SEG_Brain_Heart_Intelligence_Core_593bc09a.png",
  dashboardBrainHeartCoreClean: "/manus-storage/SEG_Dashboard_Brain_Heart_Core_Clean_Approved_45d2f500.png",
  emergencyResponse: "/manus-storage/SEG_Emergency_Response_Visual_21a05181.png",
  anatomyHologram: "/manus-storage/SEG_Human_Anatomy_Hologram_c23d102e.png",
  medicalAi: "/manus-storage/SEG_Medical_AI_Assistant_7f7b8722.png",
  medicalJournal: "/manus-storage/SEG_MedicalJournal_Reference_Final_6449012a.png",
  atlasVisualAssetsHero: "/manus-storage/SEG_ATLAS_VISUAL_ASSETS_HERO_v1.0_b0cd2819.png",
  registrationHeartStage: "/manus-storage/SEG_Registration_Approved_Heart_ECG_Stage_4079b3c9.png",
  loginOfficialLockup: "/manus-storage/SEG_Login_Official_Lockup_Transparent_Approved_d46ab5c8.png",
  loginHeartStage: "/manus-storage/SEG_Login_Heart_Intelligence_Stage_Approved_48b67481.png",
  loginBrainHeartStage: "/manus-storage/SEG_Login_Brain_Heart_Intelligence_Stage_Approved_0602fd64.png",
  landingOfficialLockup: "/manus-storage/seg-landing-official-lockup-transparent_a6d5e55a.png",
  landingAnatomyStage: "/manus-storage/seg-landing-anatomy-stage-transparent_a08ed320.png",
  landingBrainHeartStage: "/manus-storage/seg-landing-brain-heart-stage-transparent_d3aea1f3.png",
  landingEmergencyResponseStage: "/manus-storage/seg-landing-emergency-response-stage-transparent_b5e38eef.png",
  landingMedicalAssistantStage: "/manus-storage/seg-landing-medical-assistant-stage-transparent_55dbded0.png",
  landingProfileThumbnail: "/manus-storage/seg-landing-profile-thumbnail_ae4a01c8.png",
} as const;
